# Generated by Django 5.1.7 on 2025-03-21 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('autore', models.CharField(max_length=100)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('copertina', models.ImageField(blank=True, null=True, upload_to='copertine/')),
                ('categorie', models.ManyToManyField(to='libreria.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Autori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=30)),
                ('data_nascita', models.DateField()),
                ('presentazione_dell_autore', models.TextField(max_length=1000)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='autori/')),
                ('libri_scritti', models.ManyToManyField(to='libreria.libreria')),
            ],
        ),
        migrations.CreateModel(
            name='Acquisti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acquisto', models.DateTimeField(auto_now_add=True)),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oggetto_acquistato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libreria')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libreria')),
            ],
        ),
        migrations.CreateModel(
            name='Trame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trame', models.TextField(max_length=1000)),
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='libreria.libreria')),
            ],
        ),
        migrations.CreateModel(
            name='Votazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.PositiveIntegerField(choices=[(1, '1⭐'), (2, '2⭐'), (3, '3⭐'), (4, '4⭐'), (5, '5⭐')])),
                ('recensione', models.TextField(blank=True, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libreria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
