# Generated by Django 5.1.7 on 2025-03-25 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='libreria',
            name='copertina',
            field=models.ImageField(blank=True, null=True, upload_to='static/copertine'),
        ),
        migrations.CreateModel(
            name='CartaFittizia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_della_carta', models.IntegerField(max_length=16)),
                ('scadenza', models.DateField()),
                ('cvv', models.IntegerField(max_length=3)),
                ('titolare_della_carta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
