# Generated by Django 5.1.7 on 2025-03-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_alter_libreria_copertina_cartafittizia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartafittizia',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cartafittizia',
            name='numero_della_carta',
            field=models.CharField(max_length=16),
        ),
    ]
