# Generated by Django 5.1.7 on 2025-03-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_cartafittizia_cvv_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartaFittizia',
        ),
    ]
