# Generated by Django 5.1.7 on 2025-03-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_profilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilo',
            name='cognome',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilo',
            name='nome',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
