# Generated by Django 5.1.7 on 2025-03-26 10:52

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_profilo_cognome_profilo_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaFittizia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolare_della_carta', models.CharField(max_length=100)),
                ('numero_della_carta', creditcards.models.CardNumberField(max_length=25, verbose_name='card number')),
                ('data_di_scadenza', creditcards.models.CardExpiryField(verbose_name='expiration date')),
                ('cvv', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code')),
            ],
        ),
    ]
