# Generated by Django 5.1.7 on 2025-03-26 10:54

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_alter_cartafittizia_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartafittizia',
            name='cvv',
            field=creditcards.models.SecurityCodeField(max_length=3),
        ),
    ]
