# Generated by Django 5.1.7 on 2025-03-26 10:55

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_alter_cartafittizia_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartafittizia',
            name='data_di_scadenza',
            field=creditcards.models.CardExpiryField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cartafittizia',
            name='numero_della_carta',
            field=creditcards.models.CardNumberField(max_length=16),
        ),
    ]
