# Generated by Django 5.1.7 on 2025-03-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_alter_cartafittizia_data_di_scadenza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilo',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilo',
            name='data_di_nascita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
