# Generated by Django 5.1.7 on 2025-03-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_profilo_bio_profilo_data_di_nascita'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilo',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
