# Generated by Django 5.1.7 on 2025-03-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0012_profilo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartafittizia',
            name='numero_della_carta',
            field=models.CharField(max_length=16),
        ),
    ]
