# Generated by Django 5.1.7 on 2025-04-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0014_alter_votazione_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autori',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='static/autori'),
        ),
    ]
