# Generated by Django 5.1.7 on 2025-05-03 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0015_alter_autori_immagine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autori',
            name='libri_scritti',
        ),
        migrations.AlterField(
            model_name='libreria',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.autori'),
        ),
    ]
