# Generated by Django 5.1.7 on 2025-05-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_alter_autori_immagine_alter_libreria_copertina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autori',
            name='presentazione_dell_autore',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='trame',
            name='trame',
            field=models.TextField(max_length=2500),
        ),
    ]
